In [1]:
#1차원 배열 = 벡터, 2차원 이상 배열 = 매트릭스
#파이썬에서는 리스트를 이용해 유사 배열을 만드는 반면 넘파이에서는 array()함수를 사용해 리스트로 배열 생성

#★★리스트 데이터를 입력해 처리한 결과가 넘파이 배열이며 이것은 ndarray객체. 즉 파이썬 데이터 타입인 리스트 데이터를 입력하여 넘파이 배열을 생성하는 형태

#페이지 44~51

In [3]:
import numpy as np

arr1 = np.array([0, 2, 5.5, 7])  #매개변수 데이터는 리스트형
print(arr1)                      #[0.  2.  5.5 7. ]
print(arr1.shape)                #(4,) 1차원 배열
#매개변수로 입력되는 데이터가 리스트형

[0.  2.  5.5 7. ]
(4,)


In [6]:
import numpy as np

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
'''
[[1 2 3]
 [4 5 6]]
 '''
 
print(arr2.shape)                   #(2, 3) 2차원 배열. 2는 행, 3은 열 의미
print("arr2[0,2] : ", arr2[0, 2])   #=>3
 
#arr2[0,2] => 0은 리스트 데이터의 [1, 2, 3]이고, 2는 [1,2,3]중 세번째인 3의미

[[1 2 3]
 [4 5 6]]
(2, 3)
arr2[0,2] :  3


In [8]:
#배열 생성 함수
#1. numpy.zeros() 함수는 0으로 채워지는 배열 생성
arr = np.zeros(5)
print("arr : ", arr)   #[0. 0. 0. 0. 0.]

#2. shape와 dtype은 ndarray 객체의 속성
print("arr.shape : ", arr.shape)      #(5, )  => 1차원 배열이면서 요소가 5개 의미
print(arr.dtype)                      #dtype('float64)  => 배열 요소의 데이터 타입이 float64의미

arr :  [0. 0. 0. 0. 0.]
arr.shape :  (5,)
float64


In [11]:
# zero()
# zero(), ones(), empty() 함수는 배열 초기화 하는데 유용
arr = np.zeros(shape=(6,2 ))
print(arr)
'''
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
 '''

for i in range(6):
    arr[i] = (i, i)
arr

print(arr)
'''
[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]]
 '''

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]]


In [20]:
#one() => 값이 1로 채워지는 배열
#튜플형, 정수 가능
np.ones((3, 4))
'''
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
       '''

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#numpy.empty()   => 주어진 shape와 타입의 배열 생성
#정수 혹은 튜플형 가능
np.empty((2, 2), dtype=int)
'''
array([[ -54638260, 1114671495],
       [1264038849, 1325077918]])
       '''


array([[ -54638260, 1114671495],
       [1264038849, 1325077918]])

In [41]:
#numpy.eye()   => 대각선은 1, 그 밖은 0
np.eye(3,2 , dtype=int)

#k입력
#k=1 이면 1단계 위로 1 배치되고 k=-2면 대각선 기준 2단계 아래로 1이 배치
np.eye(3, k=1)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [47]:
#numpy.linspace()   => 명시된 간격으로 균등하게 분할된 값 반환
np.linspace(2.0, 3.0, num=5)  #array([2. ,2.25,2.5 ,2.75, 3.])시작2, 끝3이면서 간격을 5개 값으로 균등분할

np.linspace(2.0, 3.0, num=5, endpoint=False)    #끝 값만 포함 ㄴㄴ  array([2. , 2.2, 2.4, 2.6, 2.8])

array([2. , 2.2, 2.4, 2.6, 2.8])

In [52]:
#numpy.arange()   => 시작값 포함, 끝값 포함 x

arr1 = np.arange(5)      #[0 1 2 3 4]
arr2 = np.arange(3, 8)   #[3 4 5 6 7]


[3 4 5 6 7]


In [55]:
arr[2] = 10
arr

array([[ 0.,  0.],
       [ 1.,  1.],
       [10., 10.],
       [ 3.,  3.],
       [ 4.,  4.],
       [ 5.,  5.]])

In [82]:
#reshape
arr1 = np.arange(12)
print("arr1 : ", arr1)         #[ 0  1  2  3  4  5  6  7  8  9 10 11]

arr2 = arr1.reshape(3, 4)
print("arr2 : ", arr2)
'''[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
'''

#reshape()에 -1넣으면 다차원 배열을 1차원으로 변경
arr3 = arr2.reshape(-1)
print("arr3 : ", arr3)         #[ 0  1  2  3  4  5  6  7  8  9 10 11]   #ravel() 함수와 유사

#reshape(, )
arr4 = arr3.reshape(-1, 1)   # -1은 알수 없음을 의미. -1, 1은 행은 알수 없고 열은 1열로 하라는 것
                             # 3, -1은 행을 3열로 열은 알 수 없음으로 생성하라는 의미
'''
array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])
    '''
print("arr4 : ", arr4)

arr5 = arr3.reshape(3, -1)   # 3, -1은 행을 3열로 열은 알 수 없음으로 생성하라는 의미
print("arr5 : ", arr5)
'''
arr5 :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
'''

arr1 :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2 :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr3 :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr4 :  [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
arr5 :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


'\narr5 :  [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]\n'

In [85]:
###3차원 배열 생성
###reshape(면, 행, 열)
arr1 = np.arange(24).reshape(2, 3, 4)
print("arr1 : ", arr1)
'''[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]   => 가장 바깥쪽 대괄호2면 안에 3행이 있고 각 행 안에 4개의 열이 있는 구조'''

arr1 :  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


'[[[ 0  1  2  3]\n  [ 4  5  6  7]\n  [ 8  9 10 11]]\n\n [[12 13 14 15]\n  [16 17 18 19]\n  [20 21 22 23]]]'