In [1]:
#7.3 Numpy 2차원 배열
#page202~

In [3]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])  #list를 2차원 배열로
print(arr)
print(arr.shape)

arr2 =  arr.reshape(4,2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
abb = np.array([[1,2,3], [4,5,6]])
print("abb 구조 : ", abb)
print(abb[0])
print(abb[1])
print(abb[1,2])

abb 구조 :  [[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
6


In [19]:
abb = np.array([[1,2,3], [4,5,6]])
print(abb[1, 1:])

abc = np.array([[1,2,3], [4,5,6], [7,8,9]])

#3반 뽑아내기
print(abc[0,2])

#[[4 5 ]
# # [7 9 ]] 뽑아내기
print(abc[1:,0:2])

[5 6]
3
[[4 5]
 [7 8]]


In [22]:
#7.3.3 Axis
#행이 1, 열이 0

abcd = np.array([[1,2,3], [4,5,6]])
print("열 합 : ", abcd.sum(axis=0))
print("행 합 : ", abcd.sum(axis=1))
'''
열 합 :  [5 7 9]
행 합 :  [ 6 15]
'''

열 합 :  [5 7 9]
행 합 :  [ 6 15]


'\n열 합 :  [5 7 9]\n행 합 :  [ 6 15]\n'

In [23]:
#7.3.4 생략

In [27]:
#7.3.5 전치행렬. T나 np.transpose 사용  210쪽까지.
import numpy as np

aq = np.arange(10)
aqc = aq.reshape(2,5)
print(aqc)

aqcT = aqc.T
print(aqcT)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
