In [1]:
#페이지183 - 

In [2]:
#7-7 넘파이를 사용하지 않고 리스트를 사용한 경우
storages = [1,2,3,4]
new_s = []

for n in storages:
    n = n+n
    new_s.append(n)

print(new_s)     #[2, 4, 6, 8]

[2, 4, 6, 8]


In [3]:
#7-8 넘파이 사용
import numpy as np

st = np.array([1,2,3,4])
st = st + st
print(st)

[2 4 6 8]


In [6]:
#7.2.4. 인덱스 참조와 슬라이스
#리스트 슬라이스. 리스트는 첫 시작이 0부터이고 마지막 포함 ㄴㄴ

a = np.arange(10)
print(a)     #[0 1 2 3 4 5 6 7 8 9]

c = a[0:3]   #[0 1 2]
print(c)

a[0:3] = 4   #[4 4 4 3 4 5 6 7 8 9]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[4 4 4 3 4 5 6 7 8 9]


In [ ]:
#192 - 201쪽 추후에 다시 볼것